# Generated by Django 3.2.5 on 2023-01-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0002_auto_20230105_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='precense',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_absence',
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.FileField(default=None, max_length=300, null=True, upload_to=''),
        ),
    ]
