# Generated by Django 3.2.5 on 2023-01-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0004_student_student_absence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_absence',
        ),
    ]
