# Generated by Django 3.2.5 on 2023-01-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0008_auto_20230109_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='student',
        ),
        migrations.AddField(
            model_name='absence',
            name='student',
            field=models.ManyToManyField(to='HadirApp.Student'),
        ),
    ]
