# Generated by Django 3.2.5 on 2023-01-13 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0010_auto_20230109_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='info',
        ),
        migrations.AddField(
            model_name='absence',
            name='clas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HadirApp.class'),
        ),
        migrations.AddField(
            model_name='absence',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
