# Generated by Django 3.2.5 on 2023-01-13 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0012_auto_20230113_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
