# Generated by Django 3.2.5 on 2023-01-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0014_auto_20230113_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='info',
        ),
    ]
