# Generated by Django 3.2.5 on 2023-01-13 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0015_remove_absence_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='absence',
            name='date',
            field=models.ManyToManyField(to='HadirApp.Date'),
        ),
    ]
