# Generated by Django 3.2.5 on 2023-01-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0016_auto_20230113_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='num_of_students',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
