# Generated by Django 3.2.5 on 2023-01-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0017_class_num_of_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='classImgs',
        ),
    ]
