# Generated by Django 3.2.5 on 2023-02-01 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0018_remove_class_classimgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traning',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(default=None, null=True, upload_to='media/Traning')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_absence',
        ),
        migrations.AddField(
            model_name='class',
            name='Creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='classImgs',
            field=models.FileField(max_length=300, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HadirApp.class'),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(default=None, null=True, upload_to='media/Students'),
        ),
        migrations.AlterField(
            model_name='image',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HadirApp.student'),
        ),
    ]
