# Generated by Django 3.2.5 on 2023-02-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HadirApp', '0020_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HadirApp.student'),
        ),
    ]
